<h2>Problem 1: The Matrix Architect</h2>
Task: 1. Create a 2D NumPy array with 5 rows and 3 columns filled entirely with the number 7. 2. Change the element in the third row, second column to 10. 3. Print the following attributes of the array: ndim, shape, and dtype.


In [8]:
matrix_l  = []
for i in range(5):
    matrix_l.append([7,7,7])


In [10]:
matrix_l[2] = 10

In [14]:
matrix_l[1][0]

7

In [1]:
import numpy as np

# 1. Create a 5x3 array filled with 7s
# Note: np.full is the most direct way, or np.ones() * 7
matrix = np.full((5, 3), 7)

# 2. Update 3rd row, 2nd column (Index 2, 1)
matrix[2, 1] = 10

# 3. Print attributes
print("Array:\n", matrix)
print(f"Dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")
print(f"Data Type: {matrix.dtype}")

Array:
 [[ 7  7  7]
 [ 7  7  7]
 [ 7 10  7]
 [ 7  7  7]
 [ 7  7  7]]
Dimensions: 2
Shape: (5, 3)
Data Type: int64


In [20]:
matrix

array([[ 7,  7,  7],
       [ 7,  7,  7],
       [ 7, 20,  7],
       [ 7,  7,  7],
       [ 7,  7,  7]])


<h2>Problem 2: The Linear Navigator</h2>
Task: 1. Create a 1D array called evens that contains all even integers from 10 to 50 (inclusive). 2. Create a second 1D array called linspace_data that contains 15 equally spaced values between 0 and 100. 3. Calculate and print the total memory size (in bytes) of the evens array.

Hint: Total bytes = .size multiplied by .itemsize.


In [32]:
evens_float = np.arange(10.0, 52.0, 2)
evens_int = np.arange(10, 52, 2)

In [37]:


evens = np.array([1,2], dtype='int8')

print(evens_float.itemsize)
print(evens_int.itemsize)
print(evens.itemsize)



8
8
1


In [25]:
import numpy as np

# 1. Evens from 10 to 50
evens = np.arange(10, 52, 2)

# 2. 15 equally spaced values from 0 to 100
linspace_data = np.linspace(0, 100, 15)

# 3. Calculate total bytes
total_bytes = evens.size * evens.itemsize

print(f"Evens Array: {evens}")
print(f"Linspace Array: {linspace_data}")
print(f"Total bytes used by 'evens': {total_bytes} bytes")

Evens Array: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
Linspace Array: [  0.           7.14285714  14.28571429  21.42857143  28.57142857
  35.71428571  42.85714286  50.          57.14285714  64.28571429
  71.42857143  78.57142857  85.71428571  92.85714286 100.        ]
Total bytes used by 'evens': 168 bytes


<h2>Problem 3: The 3D Tensor Check</h2>
Task: Imagine you are storing data for a 3-day experiment. Each day, you take 4 readings from 2 different sensors.

Create a 3D array of zeros with the shape (3, 4, 2) to represent this data.

Print the size of the array.

Verify the "Rank" of the array by printing its ndim.

Explain in a comment what each number in the shape (3, 4, 2) represents based on the experiment description.

In [41]:
import numpy as np

# 1. Create 3D zeros (3 days, 4 readings, 2 sensors)
experiment_data = np.empty((3, 4, 2))
print(experiment_data)
# 2. Print size
print(f"Total number of readings (size): {experiment_data.size}")

# 3. Print rank
print(f"Array Rank (ndim): {experiment_data.ndim}")

# 4. Explanation:
# The shape (3, 4, 2) represents:
# 3: The 'depth' or number of blocks (The 3 Days)
# 4: The number of rows in each block (The 4 Readings per day)
# 2: The number of columns (The 2 Sensors per reading)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
Total number of readings (size): 24
Array Rank (ndim): 3


In [42]:
import numpy as np

# 1. Create the array
temps_f = np.array([72, 75, 68, 80, 82, 77, 74, 70, 65, 85])

# 2. Convert to Celsius (Vectorized operation)
temps_c = (temps_f - 32) * (5/9)

# 3. Round to 2 decimal places
temps_c_rounded = np.round(temps_c, 2)

print(f"Fahrenheit: {temps_f}")
print(f"Celsius:    {temps_c_rounded}")

Fahrenheit: [72 75 68 80 82 77 74 70 65 85]
Celsius:    [22.22 23.89 20.   26.67 27.78 25.   23.33 21.11 18.33 29.44]


In [ ]:
import numpy as np

prices = np.array([120, 85, 200, 45, 150])
costs = np.array([80, 60, 130, 30, 100])

# 1. Element-wise subtraction
profits = np.subtract(prices, costs) # or simply: prices - costs

# 2. Square root ufunc
roots = np.sqrt(profits)

# 3. Max ufunc
max_profit = np.max(profits)

print(f"Profits: {profits}")
print(f"Square Roots: {roots}")
print(f"Highest Profit: {max_profit}")

In [43]:
import numpy as np

# 1. Generate 10 values between 0 and 2*pi
x = np.linspace(0, 2 * np.pi, 10)

# 2. Calculate Sin and Cos
sin_x = np.sin(x)
cos_x = np.cos(x)

# 3. Sum the signals
result = sin_x + cos_x

print(f"X values: {x}")
print(f"Resulting Signal: {result}")

X values: [0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
Resulting Signal: [ 1.          1.40883205  1.15845593  0.3660254  -0.59767248 -1.28171276
 -1.3660254  -0.81115958  0.12325683  1.        ]


Find the total sales for each store (collapse the columns).Find the average sales for each month (collapse the rows).Find the highest sales figure recorded across the entire company.

In [46]:
sales = np.array([[120, 150, 130],  # Store A
                  [90, 110, 100],   # Store B
                  [200, 210, 190],  # Store C
                  [150, 140, 160]]) # Store D



total_per_store = np.sum(sales, axis=1)
print(f'Total: {total_per_store}')

avg_per_month = np.mean(sales, axis=0)
print(f'Average: {avg_per_month}')


max_sale = np.max(sales)
print(f'Highest: {max_sale}')

Total: [400 300 600 450]
Average: [140.  152.5 145. ]
Highest: 210
