In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
d0 = 'Geeks for geeks'
d1 = 'Geeks'
d2 = 'r2j'
string = [d0, d1, d2]

In [3]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(string)

In [24]:
print('\nidf values:')
for ele1, ele2 in zip(tfidf.get_feature_names_out(), tfidf.idf_):
    print(ele1, ':', ele2)


idf values:
for : 1.6931471805599454
geeks : 1.2876820724517808
r2j : 1.6931471805599454


In [29]:
print('\nWord indexes:')
print(tfidf.vocabulary_)
print('\ntf-idf value:')
print(result)
print('\ntf-idf values in matrix form:')
print(result.toarray())


Word indexes:
{'geeks': 1, 'for': 0, 'r2j': 2}

tf-idf value:
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (3, 3)>
  Coords	Values
  (0, 1)	0.8355915419449176
  (0, 0)	0.5493512310263033
  (1, 1)	1.0
  (2, 2)	1.0

tf-idf values in matrix form:
[[0.54935123 0.83559154 0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]]


In [33]:
result.toarray()

array([[0.54935123, 0.83559154, 0.        ],
       [0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        ]])

In [80]:
movie_file_path

'/Users/rafael/.cache/kagglehub/datasets/jrobischon/wikipedia-movie-plots/versions/1/wiki_movie_plots_deduped.csv'

In [84]:
import kagglehub
import pandas as pd
import os

# ==========================================
# Part 1: Wikipedia Movie Plots Dataset
# ==========================================
print("Downloading Wikipedia Movie Plots...")
# This fetches the data and returns the local directory path
movie_folder_path = kagglehub.dataset_download("jrobischon/wikipedia-movie-plots")

# Construct the full file path and load into Pandas
movie_file_path = os.path.join(movie_folder_path, "wiki_movie_plots_deduped.csv")
df_movies = pd.read_csv(movie_file_path)

print(f"Success! Loaded {len(df_movies)} movie records.")
print(df_movies[['Title', 'Genre']].head(3), "\n")


# ==========================================
# Part 2: BBC News Archive Dataset
# ==========================================
print("Downloading BBC News Archive...")
bbc_folder_path = kagglehub.dataset_download("hgultekin/bbcnewsarchive")

# Construct the full file path. 
# Note: This specific BBC dataset is tab-separated, so we use sep='\t'
bbc_file_path = os.path.join(bbc_folder_path, "bbc-news-data.csv")
df_articles = pd.read_csv(bbc_file_path, sep='\t')

print(f"Success! Loaded {len(df_articles)} news articles.")
print(df_articles[['title', 'category']].head(3))

Success! Loaded 34886 movie records.
                           Title    Genre
0         Kansas Saloon Smashers  unknown
1  Love by the Light of the Moon  unknown
2        The Martyred Presidents  unknown 

Success! Loaded 2225 news articles.
                               title  category
0  Ad sales boost Time Warner profit  business
1   Dollar gains on Greenspan speech  business
2  Yukos unit buyer faces loan claim  business


In [86]:
df_movies['Genre'].value_counts()

Genre
unknown                                      6083
drama                                        5964
comedy                                       4379
horror                                       1167
action                                       1098
                                             ... 
adventure, drama film                           1
sport film                                      1
animation, produced by glukoza production       1
adventure, romance, fantasy film                1
horror romantic comedy                          1
Name: count, Length: 2265, dtype: int64

In [37]:
df_movies['Genre'].value_counts()

Genre
drama       5964
comedy      4379
action      1098
thriller     966
romance      923
Name: count, dtype: int64

In [97]:
X_train_tfidf.toarray()[0].shape

(10000,)

In [103]:
tfidf_matrix.toarray()[0].shape

(5000,)

In [98]:
X_train_tfidf.toarray()[0].flatten().shape

(10000,)

In [88]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download NLTK data (run once)
nltk.download('stopwords')
nltk.download('wordnet')

df_movies = pd.read_csv(movie_file_path)

# Let's filter to just a few top genres to make classification easier for your first run
top_genres = ['comedy', 'drama', 'action', 'thriller', 'romance']
df_movies = df_movies[df_movies['Genre'].isin(top_genres)]

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    # Lowercase
    text = str(text).lower()
    # Remove punctuation and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Tokenize and remove stop words + lemmatize
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return ' '.join(tokens)

# Apply the preprocessing
df_movies['Clean_Plot'] = df_movies['Plot'].apply(preprocess_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/rafael/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/rafael/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [89]:
df_movies[['Plot', 'Clean_Plot','Genre' ]]

,Plot,Clean_Plot,Genre
7,The film is about a family who move to the sub...,film family move suburb hoping quiet life thin...,comedy
14,Before heading out to a baseball game at a nea...,heading baseball game nearby ballpark sport fa...,comedy
15,The plot is that of a black woman going to the...,plot black woman going dentist toothache given...,comedy
16,On a beautiful summer day a father and mother ...,beautiful summer day father mother take daught...,drama
17,A thug accosts a girl as she leaves her workpl...,thug accosts girl leaf workplace man rescue th...,drama
...,...,...,...
34874,Hasan is a twelve-year-old boy living with his...,hasan twelveyearold boy living two younger sib...,drama
34875,"Through the night, three cars carry a small gr...",night three car carry small group men police o...,drama
34876,The film opens with a Senegalese boy named Kha...,film open senegalese boy named khadim told lit...,drama
34882,"Two musicians, Salih and Gürkan, described the...",two musician salih grkan described adventure c...,comedy


In [58]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

X = df_movies['Clean_Plot']
y = df_movies['Genre']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# TfidfVectorizer actually combines CountVectorizer and TfidfTransformer into one step!
vectorizer = TfidfVectorizer(max_features=10000) 

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [59]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

predictions = model.predict(X_test_tfidf)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

      action       0.68      0.43      0.53       200
      comedy       0.68      0.70      0.69       886
       drama       0.64      0.82      0.72      1195
     romance       0.65      0.23      0.34       206
    thriller       0.64      0.13      0.21       179

    accuracy                           0.66      2666
   macro avg       0.66      0.46      0.50      2666
weighted avg       0.66      0.66      0.63      2666



In [42]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))

[[ 88  30  72   4   6]
 [  7 630 239   5   5]
 [ 22 189 958  21   5]
 [  9  44 102  50   1]
 [  8  33 107   2  29]]


In [ ]:
# Train the entire pipeline at once
text_clf_pipeline.fit(X_train_art, y_train_art)


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression



df_article = pd.read_csv(bbc_file_path, sep='\t')

# Separate data
X_art = df_articles['content']
y_art = df_articles['category']
X_train_art, X_test_art, y_train_art, y_test_art = train_test_split(X_art, y_art, test_size=0.2, random_state=42)

# Create a Pipeline
# This time, let's explicitly use CountVectorizer followed by TfidfTransformer to see how they chain
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

text_clf_pipeline = Pipeline([
    ('vect', CountVectorizer(max_features=10000, ngram_range=(1, 2))), # Includes bigrams!
    ('tfidf', TfidfTransformer()),
    ('clf', LogisticRegression(max_iter=1000)), # Logistic Regression works great for text
])

# Train the entire pipeline at once
text_clf_pipeline.fit(X_train_art, y_train_art)

# Evaluate
art_predictions = text_clf_pipeline.predict(X_test_art)
print("Article Classification Report:\n")
print(classification_report(y_test_art, art_predictions))

Article Classification Report:

               precision    recall  f1-score   support

     business       0.94      0.97      0.95       115
entertainment       0.97      0.96      0.97        72
     politics       0.95      0.95      0.95        76
        sport       0.99      0.99      0.99       102
         tech       0.96      0.94      0.95        80

     accuracy                           0.96       445
    macro avg       0.96      0.96      0.96       445
 weighted avg       0.96      0.96      0.96       445



In [83]:
print(confusion_matrix(y_test_art, art_predictions))

[[111   0   3   0   1]
 [  1  69   1   0   1]
 [  2   0  72   1   1]
 [  1   0   0 101   0]
 [  3   2   0   0  75]]


Advanced topics

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. Initialize and fit the TF-IDF Vectorizer
# We limit max_features to keep it computationally light and use english stop words
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
tfidf_matrix = vectorizer.fit_transform(df_movies['Clean_Plot'])

# 2. Extract the vocabulary (the actual words)
feature_names = np.array(vectorizer.get_feature_names_out())

# 3. Create a helper function to grab the top words row by row
def get_top_keywords_for_all(tfidf_matrix, features, top_n=5):
    all_keywords = []
    
    # Iterate through each document (row) in the sparse matrix
    for row in tfidf_matrix:
        # Convert the single row to a dense array so we can sort it
        row_data = row.toarray().flatten()
        
        # Get the indices of the highest scores (argsort sorts ascending, so we take the end and reverse)
        top_indices = row_data.argsort()[-top_n:][::-1]
        
        # Map indices back to the actual words, ignoring words with a score of 0
        top_words = [features[i] for i in top_indices if row_data[i] > 0]
        
        # Join them into a single string (e.g., "alien, space, ship") and add to our list
        all_keywords.append(", ".join(top_words))
        
    return all_keywords

# 4. Apply the function and create a new column in your DataFrame
df_movies['Top_Keywords'] = get_top_keywords_for_all(tfidf_matrix, feature_names, top_n=5)

# 5. Check out the results!
df_movies[['Clean_Plot', 'Top_Keywords']].head()

TypeError: sequence item 0: expected str instance, numpy.ndarray found

In [66]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Assuming you have your train/test split ready from the articles dataset
# X_train_art, X_test_art, y_train_art, y_test_art 

# 1. Set up the Pipeline
# We can use TfidfVectorizer directly instead of combining CountVectorizer + TfidfTransformer
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(stop_words='english')),
    ('clf', LogisticRegression(max_iter=1000, random_state=42))
])

# 2. Define the Parameter Grid
# Note the syntax: stepname__parametername (with a double underscore in between)
param_grid = {
    # Test Unigrams alone, Unigrams + Bigrams, and Unigrams + Bigrams + Trigrams
    'tfidf__ngram_range': [(1, 1), (1, 2), (1, 3)], 
    
    # Test different vocabulary limits (None means it will use all available features)
    'tfidf__max_features': [1000, 3000, 5000, None],
    
    # Optional: You can even test Logistic Regression hyperparameters at the same time!
    # 'clf__C': [0.1, 1.0, 10.0] 
}

# 3. Initialize the Grid Search
# cv=3 means 3-fold cross-validation. 
# n_jobs=-1 tells your machine to use all available CPU cores to speed up the process.
grid_search = GridSearchCV(pipeline, param_grid, cv=3, n_jobs=-1, verbose=1)

# 4. Run the Grid Search
print("Starting Grid Search... (This will fit multiple models, so it may take a moment!)")
grid_search.fit(X_train, y_train)

# 5. Evaluate the Results
print("\n--- Grid Search Complete ---")
print("Best Parameters found:")
for param, value in grid_search.best_params_.items():
    print(f"  - {param}: {value}")
    
print(f"Best Cross-Validation Accuracy: {grid_search.best_score_:.4f}\n")

# 6. Test the best model on your unseen test data
best_model = grid_search.best_estimator_
final_predictions = best_model.predict(X_test)

print("Classification Report using the Best Model:")
print(classification_report(y_test, final_predictions))

Starting Grid Search... (This will fit multiple models, so it may take a moment!)
Fitting 3 folds for each of 12 candidates, totalling 36 fits

--- Grid Search Complete ---
Best Parameters found:
  - tfidf__max_features: 5000
  - tfidf__ngram_range: (1, 2)
Best Cross-Validation Accuracy: 0.6197

Classification Report using the Best Model:
              precision    recall  f1-score   support

      action       0.67      0.47      0.55       200
      comedy       0.66      0.69      0.68       886
       drama       0.64      0.79      0.71      1195
     romance       0.59      0.23      0.33       206
    thriller       0.62      0.16      0.25       179

    accuracy                           0.65      2666
   macro avg       0.64      0.47      0.50      2666
weighted avg       0.64      0.65      0.63      2666



In [71]:
from tqdm import tqdm
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Assumptions: X_train_art, X_test_art, y_train_art, y_test_art are already defined

# The specific feature sizes you want to test
feature_sizes = [200, 500, 1000, 2500, 5000, 10000, 20000, 50000, 100000]

# List to store our results for easy viewing later
results = []

# Wrap the list in tqdm() to generate the progress bar
for size in tqdm(feature_sizes, desc="Evaluating max_features"):
    
    # 1. Initialize the Vectorizer and Classifier for the current iteration
    # (Keeping ngram_range=(1, 2) based on our previous setup for better context)
    vectorizer = TfidfVectorizer(max_features=size, stop_words='english', ngram_range=(1, 2))
    clf = LogisticRegression(max_iter=1000, random_state=42)
    
    # 2. Fit and transform the training data, but ONLY transform the test data
    X_train_vec = vectorizer.fit_transform(X_train)
    X_test_vec = vectorizer.transform(X_test)
    
    # 3. Train the Logistic Regression model
    clf.fit(X_train_vec, y_train)
    
    # 4. Make predictions on the test set
    predictions = clf.predict(X_test_vec)
    
    # 5. Calculate accuracy and store it
    acc = accuracy_score(y_test, predictions)
    results.append((size, acc))

# Print the final summary once the loop is completely finished
print("\n--- Results Summary ---")
for size, acc in results:
    print(f"Max Features: {size:<5} | Accuracy: {acc:.4f}")

Evaluating max_features:   0%|          | 0/9 [00:00<?, ?it/s]

Evaluating max_features: 100%|██████████| 9/9 [00:55<00:00,  6.18s/it]


--- Results Summary ---
Max Features: 200   | Accuracy: 0.5724
Max Features: 500   | Accuracy: 0.6125
Max Features: 1000  | Accuracy: 0.6302
Max Features: 2500  | Accuracy: 0.6459
Max Features: 5000  | Accuracy: 0.6478
Max Features: 10000 | Accuracy: 0.6549
Max Features: 20000 | Accuracy: 0.6515
Max Features: 50000 | Accuracy: 0.6459
Max Features: 100000 | Accuracy: 0.6455


In [77]:
!pip3 install lightgbm

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 1.6 MB 1.9 MB/s eta 0:00:01
     |████████████████████████████████| 30.3 MB 2.6 MB/s eta 0:00:011
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


OSError: dlopen(/Users/rafael/projects/ml_bootcamp/.venv/lib/python3.13/site-packages/lightgbm/lib/lib_lightgbm.dylib, 0x0006): Library not loaded: @rpath/libomp.dylib
  Referenced from: <D44045CD-B874-3A27-9A61-F131D99AACE4> /Users/rafael/projects/ml_bootcamp/.venv/lib/python3.13/site-packages/lightgbm/lib/lib_lightgbm.dylib
  Reason: tried: '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/local/lib/libomp/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libomp/libomp.dylib' (no such file), '/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libomp/lib/libomp.dylib' (no such file), '/opt/local/lib/libomp/libomp.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/local/lib/libomp/libomp.dylib' (no such file), '/Users/rafael/.local/share/uv/python/cpython-3.13.13-macos-aarch64-none/lib/libomp.dylib' (no such file), '/Users/rafael/.local/share/uv/python/cpython-3.13.13-macos-aarch64-none/lib/libomp.dylib' (no such file)

In [112]:
df_movies.iloc[5973]

Release Year                                                     1997
Title                                                   Suicide Kings
Origin/Ethnicity                                             American
Director                                               Peter O'Fallon
Cast                    Christopher Walken, Denis Leary, Henry Thomas
Genre                                                           drama
Wiki Page                 https://en.wikipedia.org/wiki/Suicide_Kings
Plot                Charlie Barret walks to his private table in a...
Clean_Plot          charlie barret walk private table restaurant s...
Top_Keywords                        charlie, max, ira, charlies, thug
Name: 13143, dtype: object

In [23]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, adjusted_rand_score

# =====================================================================
# 0. PREPARATION & ASSUMPTIONS
# =====================================================================
# Assuming df_movies and df_articles are already loaded and preprocessed 
# from our previous steps.
# Movies text: df_movies['Clean_Plot'] | Target: df_movies['Genre']
# Articles text: df_articles['content'] (Let's assume it's preprocessed into 'Clean_Content') | Target: df_articles['category']

print("Initializing Advanced Text Analytics Pipeline...")

# Let's vectorize both datasets using a researcher-grade TF-IDF setup
# (Removing corpus-specific stop words and limiting features for computational efficiency)
movie_vectorizer = TfidfVectorizer(max_features=3000, min_df=2, max_df=0.95)
X_movies_tfidf = movie_vectorizer.fit_transform(df_movies['Clean_Plot'])

article_vectorizer = TfidfVectorizer(max_features=3000, min_df=2, max_df=0.95)
X_articles_tfidf = article_vectorizer.fit_transform(df_articles['content'])


# =====================================================================
# TASK 1A: DOCUMENT SIMILARITY (Information Retrieval)
# =====================================================================
def get_top_similar_documents(tfidf_matrix, dataframe, text_col, doc_index, top_n=3):
    """
    Computes pairwise cosine similarity between a target document and the rest of the corpus.
    """
    # Compute similarity of the selected document against ALL documents in the matrix
    cosine_sim = cosine_similarity(tfidf_matrix[doc_index], tfidf_matrix).flatten()
    
    # Sort indices by highest similarity score (excluding the document itself, which is index -1 after sorting)
    similar_indices = cosine_sim.argsort()[-(top_n + 1):-1][::-1]
    
    print(f"\n--- Target Document (Index {doc_index}) ---")
    print(f"Original Text snippet: {dataframe[text_col].iloc[doc_index][:150]}...\n")
    print(f"Top {top_n} Most Similar Documents:")
    
    for idx in similar_indices:
        score = cosine_sim[idx]
        print(f"- [Doc Index {idx}] (Similarity Score: {score:.4f}): {dataframe[text_col].iloc[idx][:120]}...")

# Execute Similarity Diagnostics
print("\n=== RUNNING DOCUMENT SIMILARITY DISCOVERY ===")
get_top_similar_documents(X_movies_tfidf, df_movies, 'Plot', doc_index=42, top_n=2)
get_top_similar_documents(X_articles_tfidf, df_articles, 'content', doc_index=10, top_n=2)


# =====================================================================
# TASK 1B: DOCUMENT CLUSTERING & UNSUPERVISED EVALUATION
# =====================================================================
def perform_clustering_analysis(tfidf_matrix, dataframe, target_col, num_clusters, vectorizer):
    """
    Clusters documents using K-Means, maps clusters back to text features, 
    and validates cluster purity using mathematical metrics.
    """
    # Fit K-Means
    kmeans = KMeans(n_clusters=num_clusters, init='k-means++', max_iter=300, random_state=42)
    cluster_labels = kmeans.fit_predict(tfidf_matrix)
    
    # Mathematical Evaluation
    sil_score = silhouette_score(tfidf_matrix, cluster_labels, sample_size=2000, random_state=42)
    # Adjusted Rand Index measures agreement between cluster assignments and true labels (-1 to 1)
    ari_score = adjusted_rand_score(dataframe[target_col], cluster_labels)
    
    print(f"\n--- Clustering Metrics (K={num_clusters}) ---")
    print(f"Mean Silhouette Coefficient: {sil_score:.4f} (Closer to 1 = distinct, well-separated clusters)")
    print(f"Adjusted Rand Index (ARI): {ari_score:.4f} (Closer to 1 = perfectly matches ground-truth labels)")
    
    # Top Terms Per Cluster (Centroid Analysis)
    print("\nTop Terms per Cluster Centroid:")
    order_centroids = kmeans.cluster_centers_.argsort()[:, ::-1]
    terms = vectorizer.get_feature_names_out()
    
    for i in range(num_clusters):
        top_terms = [terms[ind] for ind in order_centroids[i, :7]]
        print(f"  Cluster {i}: {', '.join(top_terms)}")
        
    return cluster_labels

# Execute Clustering (Using 5 clusters for both since they roughly map to our 5 target classes)
print("\n=== RUNNING UNSUPERVISED MOVIE CLUSTERING ===")
df_movies['Cluster'] = perform_clustering_analysis(X_movies_tfidf, df_movies, 'Genre', num_clusters=5, vectorizer=movie_vectorizer)

print("\n=== RUNNING UNSUPERVISED ARTICLE CLUSTERING ===")
df_articles['Cluster'] = perform_clustering_analysis(X_articles_tfidf, df_articles, 'category', num_clusters=5, vectorizer=article_vectorizer)


# =====================================================================
# TASK 2: KEYWORD EXTRACTION via TF-IDF Weight Matrix
# =====================================================================
def extract_tfidf_keywords(tfidf_matrix, vectorizer, doc_index, top_n=5):
    """
    Extracts the highest-weighted terms unique to a specific document inside the corpus.
    """
    feature_names = vectorizer.get_feature_names_out()
    
    # Get the row vector for the specific document
    doc_vector = tfidf_matrix[doc_index].toarray().flatten()
    
    # Sort indices by highest TF-IDF score
    top_keyword_indices = doc_vector.argsort()[-top_n:][::-1]
    
    # Return terms paired with their mathematical weights
    keywords = [(feature_names[i], doc_vector[i]) for i in top_keyword_indices if doc_vector[i] > 0]
    return keywords

# Execute Keyword Extraction Diagnostics
print("\n=== RUNNING DETERMINISTIC KEYWORD EXTRACTION ===")
movie_idx = 105
movie_kw = extract_tfidf_keywords(X_movies_tfidf, movie_vectorizer, doc_index=movie_idx)
print(f"\nTop Keywords for Movie Index {movie_idx} (Plot: {df_movies['Plot'].iloc[movie_idx][:100]}...):")
for word, score in movie_kw:
    print(f"  - {word}: {score:.4f}")

article_idx = 250
article_kw = extract_tfidf_keywords(X_articles_tfidf, article_vectorizer, doc_index=article_idx)
print(f"\nTop Keywords for Article Index {article_idx} (Content: {df_articles['content'].iloc[article_idx][:100]}...):")
for word, score in article_kw:
    print(f"  - {word}: {score:.4f}")

Initializing Advanced Text Analytics Pipeline...

=== RUNNING DOCUMENT SIMILARITY DISCOVERY ===

--- Target Document (Index 42) ---
Original Text snippet: Charlie offers Mabel a ride on his two-seater motorcycle, which she accepts in preference to his rival's racing car. Unfortunately as they go over a b...

Top 2 Most Similar Documents:
- [Doc Index 5973] (Similarity Score: 0.5309): Charlie Barret walks to his private table in a restaurant, only to see two young men sitting at his table – Avery and Ma...
- [Doc Index 44] (Similarity Score: 0.5003): Chaplin, in tramp attire, sits in the park with his wife, Mabel. While he is gone to a bar, a large man holding a tennis...

--- Target Document (Index 10) ---
Original Text snippet:  Ask Jeeves has become the third leading online search firm this week to thank a revival in internet advertising for improving fortunes.  The firm's r...

Top 2 Most Similar Documents:
- [Doc Index 2141] (Similarity Score: 0.3970):  Ask Jeeves has bought the Bl